name: Deploy to Glitch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to Glitch
      env:
        GLITCH_GIT_URL: https://72cba5a9-5876-452b-8a31-a910ea77a485@api.glitch.com/git/bony-nasal-postage
        GLITCH_API_TOKEN: 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
        GLITCH_PROJECT: bony-nasal-postage
      run: |
        curl -X POST "https://api.glitch.com/projects/${{ env.GLITCH_PROJECT }}/git/import" \
          -d '{"url": "${{ env.GLITCH_GIT_URL }}"}' \
          -H "Authorization: Bearer ${{ env.GLITCH_API_TOKEN }}"
